/* eslint-disable prettier/prettier */
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';
import { MongoDBID } from 'src/types/schema.types';

@Schema()
export class Project extends Document {
  // _id is auto-generated by Mongoose as the primary key

  @Prop({ type: Types.ObjectId, ref: 'User', required: true })
  userId: Types.ObjectId;

  @Prop({ required: true })
  projectName: string;
}

export const ProjectSchema = SchemaFactory.createForClass(Project);
export type ProjectDocument = Project & Document & MongoDBID

// Index for faster lookup by userId
ProjectSchema.index({ userId: 1 });
