/* eslint-disable prettier/prettier */
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';
import { MongoDBID } from 'src/types/schema.types';

@Schema()
export class User extends Document {
  // _id is auto-generated by Mongoose as the primary key

  @Prop({ required: true, unique: true })
  email: string;

  @Prop({ required: true })
  passwordHash: string;
}

export type UserDocument = User & Document & MongoDBID;
export const UserSchema = SchemaFactory.createForClass(User);